spring:
    application:
        name: configuration-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/BrunoCaetanoDev/configuration-repository.git
                    default-label: main
                    searchPaths: '{application}'
server:
    port: ${SERVER_PORT:8888}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: configuration-server